#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
git clone https://github.com/najahiiii/aarch64-linux-gnu.git -b linaro8-20190216 gcc
git clone https://github.com/najahiiii/clang.git -b llvm9 llvm9
GCC="$(pwd)/gcc/bin/aarch64-linux-gnu-"
CT="$(pwd)/llvm9/bin/clang"
curl -s -F chat_id=-1001158707255 -F sticker="CAADBQAD3AADfULDLpHzWZltpdJ5FgQ" https://api.telegram.org/bot961309167:AAHAtYQIDZgCpL8V_Pn5LYyozC5V0KJy3SE/sendSticker
curl -s -X POST https://api.telegram.org/bot961309167:AAHAtYQIDZgCpL8V_Pn5LYyozC5V0KJy3SE/sendMessage?chat_id=-1001158707255 -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>SteelHeart CI new build is up!!</b>%0A<b>Compile Started !!</b>%0A<b>For device</b> <code>Riva (Redmi 5A)</code>%0A<b>For Android Oreo or Android Pie</b>%0A<b>Under Commit</b> <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0A<b>Compiler</b> <code>$(${GCC}gcc --version | head -n 1)</code>%0A<b>Clang</b> <code>$(${CT} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</code>%0A<b>Started on</b> <code>$(TZ=Asia/Jakarta date)</code>%0A<b>Tree:</b> #Sunny"
tanggal=$(TZ=Asia/Jakarta date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=mmhmdfas
export KBUILD_BUILD_HOST=Drone-CI-VM
export USE_CCACHE=1
export CACHE_DIR=~/.ccache
# Fin Error
function finerr() {
        curl -s -X POST https://api.telegram.org/bot961309167:AAHAtYQIDZgCpL8V_Pn5LYyozC5V0KJy3SE/sendMessage?chat_id=-1001158707255 -d "disable_web_page_preview=true" -d "parse_mode=html&text=Build throw an error(s)"
        exit 1
}
make -s -C $(pwd) -j48 O=out riva_defconfig
make -s -C $(pwd) CC=${CT} CCROSS_COMPILE=${GCC} O=out -j60 -l50 2>&1| tee build.log
if ! [ -a $IMAGE ]; then
	exit 1
fi
cp out/arch/arm64/boot/Image.gz-dtb anykornol/zImage
paste
cd anykornol
zip -r9 perf-gcommon-${tanggal}.zip *
END=$(date +"%s")
DIFF=$(($END - $START))
curl -F chat_id="-1001158707255" -F document=@"perf-gcommon-${tanggal}.zip " -F "disable_web_page_preview=true" -F "parse_mode=html" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). |<b> For Xiaomi Redmi 5A </b>| #nightly | <b>$(${CT} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</b>" https://api.telegram.org/bot961309167:AAHAtYQIDZgCpL8V_Pn5LYyozC5V0KJy3SE/sendDocument
cd ..
echo "end build"
