#!bin/bash
echo "Clone Dependencies"
git clone --quiet -j32 https://github.com/crDroidMod/android_prebuilts_clang_host_linux-x86_clang-5900059 -b 9.0 --depth=1 clang
git clone --quiet -j32 https://github.com/fadlyas07/android-prebuilts-aarch64-mirror -b linaro-7.4.1 --depth=1 gpu
git clone --quiet -j32 https://github.com/fadlyas07/AnyKernel3 --depth=1 anykernel3
echo "2nd Build"
git clone --quiet -j32 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-9.0.0_r39 --depth=1 gcc
git clone --quiet -j32 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-9.0.0_r39 --depth=1 gcc32
git clone --quiet -j32 https://github.com/fadlyas07/AnyKernel3 --depth=1 anykernel
echo "done"
if [ "$is_test" = true ]; then
     echo "Its alpha test build"
     unset chat_id
     unset token
     export chat_id=784548477
     export token='https://api.telegram.org/bot961309167:AAHAtYQIDZgCpL8V_Pn5LYyozC5V0KJy3SE'
else
     echo "Its beta release build"
fi
CT="$(pwd)/clang/bin/clang"
GPU="$(pwd)/gpu/bin/aarch64-linux-gnu-"
GCC="$(pwd)/gcc/bin/aarch64-linux-android-"
GCC32="$(pwd)/gcc32/bin/aarch64-linux-androideabi-"
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
NUM=$(echo $CIRCLE_BUILD_NUM | cut -c 1-2)
TANGGAL=$(TZ=Asia/Jakarta date +'%H%M-%d%m%y')
START=$(date +"%s")
export TZ=":Asia/Jakarta"
export ARCH=arm64
export KBUILD_BUILD_USER=Mhmmdfas
export KBUILD_BUILD_HOST=SteelHeart-CI-${NUM}
export USE_CCACHE=1
export CACHE_DIR=~/.ccache
# sticker plox
function sticker() {
        curl -s -X POST "https://api.telegram.org/bot961309167:AAHAtYQIDZgCpL8V_Pn5LYyozC5V0KJy3SE/sendSticker" \
                        -d sticker="CAADBQAD3AADfULDLpHzWZltpdJ5FgQ" \
                        -d chat_id=-1001158707255
}
# Send info plox
function sendinfo() {
        curl -s -X POST "https://api.telegram.org/bot961309167:AAHAtYQIDZgCpL8V_Pn5LYyozC5V0KJy3SE/sendMessage" \
                        -d chat_id=-1001158707255 \
                        -d "disable_web_page_preview=true" \
                        -d "parse_mode=html" \
                        -d text="<b>SteelHeart CI new build is up</b>!!%0AFor device: <code>Xiaomi Redmi 4A</code>%0AFrom branch: <code>$(git rev-parse --abbrev-ref HEAD)</code> %0AKernel Version: <code>3.18.140</code>%0AFor Android: <code>8.1-9.0</code>%0ACommit message <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0ACompiled with: <code>$(${CT} --version | head -n 1 | perl -pe 's/\(.*?\)//gs' | sed -e 's/  */ /g')</code>%0A<b>And the 2nd Build</b>%0ACompiled With: <code>$(${GCC}gcc --version | head -n 1)</code>%0AStarted on: <code>$(TZ=Asia/Jakarta date)</code>%0A<b>Build Status:</b> #Untested"
}
# Send private info
function sendpriv() {
        curl -s -X POST "https://api.telegram.org/bot961309167:AAHAtYQIDZgCpL8V_Pn5LYyozC5V0KJy3SE/sendMessage" \
                        -d chat_id=784548477 \
                        -d "disable_web_page_preview=true" \
                        -d "parse_mode=html" \
                        -d text="SteelHeart new build coming!%0ACompile di mulai pada [<code>$(TZ=Asia/Jakarta date)</code>]%0ALink CI <a href='${CIRCLE_BUILD_URL}'>TAP</a> | #${NUM}."
}
# Push kernel to channel
function push() {
        cd anykernel3
	ZIP=$(echo Steelheart-clang*.zip)
	curl -F document=@$ZIP "https://api.telegram.org/bot961309167:AAHAtYQIDZgCpL8V_Pn5LYyozC5V0KJy3SE/sendDocument" \
			-F chat_id="-1001158707255" \
			-F "disable_web_page_preview=true" \
			-F "parse_mode=html" \
			-F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). <b>For Xiaomi Redmi 4A</b> [ <code>$UTS</code> ]"
}
# Fin Error
function finerr() {
        paste
        curl -s -X POST "https://api.telegram.org/bot961309167:AAHAtYQIDZgCpL8V_Pn5LYyozC5V0KJy3SE/sendMessage" \
			-d chat_id="-1001158707255" \
			-d "disable_web_page_preview=true" \
			-d "parse_mode=markdown" \
			-d text="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s) but it's error..."
        exit 1
}
# Compile plox
function compile() {
        make -s -C $(pwd) O=out rolex_defconfig
        make -s -C $(pwd) CC=${CT} CROSS_COMPILE=${GPU} O=out -j60 -l50 2>&1| tee build.log
        UTS=$(cat out/include/generated/compile.h | grep UTS_VERSION | cut -d '"' -f2)
            if ! [ -a $IMAGE ]; then
                finerr
                exit 1
            fi
        cp out/arch/arm64/boot/Image.gz-dtb anykernel3/zImage
        paste
}
# Zipping
function zipping() {
    cd anykernel3 || exit 1
    if [ "$is_test" = true ]; then
        zip -r9 Steelheart-clang-ALPHA-"${TANGGAL}".zip * -x .git README.md
    else
        zip -r9 Steelheart-clang-"${TANGGAL}".zip * -x .git README.md
    fi
    cd ..
}
echo "belom beres"
# Push again
function push() {
        cd anykernel3
	ZIP=$(echo Steelheart-gcc*.zip)
	curl -F document=@$ZIP "https://api.telegram.org/bot961309167:AAHAtYQIDZgCpL8V_Pn5LYyozC5V0KJy3SE/sendDocument" \
			-F chat_id="-1001158707255" \
			-F "disable_web_page_preview=true" \
			-F "parse_mode=html" \
			-F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). <b>For Xiaomi Redmi 4A</b> [ <code>$UTS</code> ]"
}
# Fin Problem
function finerr() {
        paste
        curl -s -X POST "https://api.telegram.org/bot961309167:AAHAtYQIDZgCpL8V_Pn5LYyozC5V0KJy3SE/sendMessage" \
			-d chat_id="-1001158707255" \
			-d "disable_web_page_preview=true" \
			-d "parse_mode=markdown" \
			-d text="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s) but it's error..."
        exit 1
}
# Compile Again
function compile() {
        make -s -C $(pwd) O=out rolex_defconfig
        make -s -C $(pwd) CROSS_COMPILE=${GCC} CROSS_COMPILE_ARM32=${GCC32} O=out -j60 -l50 2>&1| tee build.log
        UTS=$(cat out/include/generated/compile.h | grep UTS_VERSION | cut -d '"' -f2)
            if ! [ -a $IMAGE ]; then
                finerr
                exit 1
            fi
        cp out/arch/arm64/boot/Image.gz-dtb anykernel/zImage
        paste
}
# Zipping Again
function zipping() {
    cd anykernel || exit 1
    if [ "$is_test" = true ]; then
        zip -r9 Steelheart-gcc-ALPHA-"${TANGGAL}".zip * -x .git README.md
    else
        zip -r9 Steelheart-gcc-"${TANGGAL}".zip * -x .git README.md
    fi
    cd ..
}
rm -rf out
rm -rf anykernel3
sticker
sendinfo
sendpriv
compile
zipping
END=$(date +"%s")
DIFF=$(($END - $START))
push
Compileagain
Zippingagain
END=$(date +"%s")
DIFF=$(($END - $START))
pushagain
